export const localeNames = {
  ja: '日本語', 'ja-x-easy': 'やさしい日本語', en: 'English', 'zh-Hans': '简体中文', 'zh-Hant': '繁體中文', ko: '한국어', pt: 'Português', es: 'Español', vi: 'Tiếng Việt', tl: 'Filipino / Tagalog', ne: 'नेपाली', id: 'Bahasa Indonesia', th: 'ไทย', hi: 'हिन्दी', fr: 'Français', ru: 'Русский',
} as const;

export type Locale = keyof typeof localeNames;

const en = {
  emergency: 'EMERGENCY', callFirst: 'Call 119 first', cpr: 'Start CPR. Ask another person to get the AED.', call: 'CALL', findLabel: 'FIND NEAREST', findTitle: 'Point me to an AED', findBody: 'We compare your position with verified municipal listings and show the three nearest options.', useLocation: 'Use my location', privacy: 'Nothing is stored or sent', demo: 'Try central Tokyo demo', locating: 'Finding your position…', loadError: 'The AED snapshot could not be loaded.', locationDenied: 'Location access was denied. You can still try the demo.', locationError: 'Your position is unavailable. Try again outside or use the demo.', nearest: 'Nearest listed AED', straightLine: 'straight-line', open24: 'Listed as 24-hour', accessUnknown: 'Access unknown', officialListing: 'Official Japanese listing', route: 'Open walking route', routeLeaves: 'Opens an external map', compass: 'Use phone compass', northUp: 'North-up bearing', bearing: 'bearing', changeWarning: 'Data may have changed — confirm access on arrival.', source: 'Source', snapshot: 'App snapshot', back: 'Start again', pilot: 'Tokyo pilot', varies: 'Coverage varies by municipality', sourced: 'municipalities sourced', arrowWarning: 'Direction to listed coordinates—not a verified entrance.', coverage: 'Coverage & sources', candidates: 'Other nearby listings', close: 'Close', language: 'Choose language', reviewPending: 'Pilot translations — human review is required before public release.', noLocalData: 'Verified municipal data is not yet available in this pilot.', nationwideMap: 'Open the nationwide AED map', records: 'listed AEDs', validated: 'with coordinate-valid records', placement: 'Placement', demoLabel: 'DEMO POSITION', liveLabel: 'YOUR POSITION', loadingData: 'Loading the verified snapshot…',
};
export type Messages = typeof en;

const translations: Partial<Record<Locale, Partial<Messages>>> = {
  ja: { emergency: '緊急', callFirst: 'まず119番へ電話', cpr: '心肺蘇生を始めてください。別の人にAEDを取りに行ってもらってください。', call: '電話', findLabel: '近くを探す', findTitle: '近くのAEDへ案内', findBody: '現在地と自治体の公開データを比較し、近い3か所を表示します。', useLocation: '現在地を使う', privacy: '現在地は保存・送信しません', demo: '東京都心のデモを試す', locating: '現在地を確認しています…', locationDenied: '位置情報が許可されていません。デモは利用できます。', locationError: '現在地を取得できません。屋外で再試行するか、デモを利用してください。', nearest: '最も近い掲載AED', straightLine: '直線距離', open24: '24時間利用可能と掲載', accessUnknown: '利用可能時間は不明', officialListing: '公式の日本語情報', route: '徒歩ルートを開く', routeLeaves: '外部の地図を開きます', compass: 'スマートフォンのコンパスを使う', northUp: '北を上にした方角', bearing: '方位', changeWarning: '情報が変わっている場合があります。到着時に利用できるか確認してください。', source: '出典', snapshot: 'アプリのデータ取得日', back: '最初に戻る', pilot: '東京パイロット', varies: '自治体によりデータ範囲が異なります', sourced: '自治体の出典あり', arrowWarning: '矢印は掲載座標への方向です。入口を保証するものではありません。', coverage: '対応地域と出典', candidates: '近くのほかの掲載場所', close: '閉じる', language: '言語を選ぶ', reviewPending: '公開前に専門家による翻訳確認が必要です。', noLocalData: 'このパイロットには、確認済みの自治体データがありません。', nationwideMap: '全国AEDマップを開く', records: '掲載AED', validated: '座標確認済み', placement: '設置場所', demoLabel: 'デモ位置', liveLabel: '現在地', loadingData: '確認済みデータを読み込んでいます…' },
  'ja-x-easy': { emergency: 'きんきゅう', callFirst: 'まず 119に でんわ', cpr: '心ぞうマッサージを はじめます。ほかの人に AEDを とりに いってもらいます。', call: 'でんわ', findLabel: 'ちかくを さがす', findTitle: 'AEDの ほうこうを しる', findBody: 'あなたの ばしょから ちかい AEDを 3つ みせます。', useLocation: 'いまの ばしょを つかう', privacy: 'ばしょは のこしません。おくりません。', demo: 'とうきょうの デモを ためす', locating: 'いまの ばしょを しらべています…', nearest: 'いちばん ちかい AED', straightLine: 'まっすぐの きょり', open24: '24じかん つかえる リスト', accessUnknown: 'つかえる じかんは わかりません', route: 'あるく みちを ひらく', changeWarning: 'じょうほうが かわっているかも しれません。ついたら つかえるか たしかめます。', back: 'はじめに もどる', coverage: 'つかえる ちいき・データ', candidates: 'ほかの ちかい AED', placement: 'おいてある ばしょ' },
  'zh-Hans': { emergency: '紧急', callFirst: '请先拨打119', cpr: '立即开始心肺复苏。请他人去取AED。', call: '拨打', findTitle: '指引我前往AED', useLocation: '使用我的位置', privacy: '不会保存或发送位置', demo: '尝试东京市中心演示', locating: '正在获取您的位置…', nearest: '最近的已列出AED', straightLine: '直线距离', open24: '标示为24小时可用', accessUnknown: '开放时间未知', route: '打开步行路线', changeWarning: '数据可能已变更—到达时请确认是否可以使用。', coverage: '覆盖范围与来源' },
  'zh-Hant': { emergency: '緊急', callFirst: '請先撥打119', cpr: '立即開始心肺復甦。請他人去取AED。', call: '撥打', findTitle: '指引我前往AED', useLocation: '使用我的位置', privacy: '不會儲存或傳送位置', demo: '試用東京都心示範', locating: '正在取得您的位置…', nearest: '最近的已列出AED', straightLine: '直線距離', open24: '標示為24小時可用', accessUnknown: '開放時間未知', route: '開啟步行路線', changeWarning: '資料可能已變更—抵達時請確認是否可以使用。', coverage: '涵蓋範圍與來源' },
  ko: { emergency: '긴급', callFirst: '먼저 119에 전화하세요', cpr: '심폐소생술을 시작하세요. 다른 사람에게 AED를 가져오게 하세요.', call: '전화', findTitle: '가까운 AED 방향 보기', useLocation: '내 위치 사용', privacy: '위치는 저장하거나 전송하지 않습니다', demo: '도쿄 중심부 데모', locating: '현재 위치를 찾는 중…', nearest: '가장 가까운 등록 AED', straightLine: '직선 거리', open24: '24시간 이용 가능으로 표시', accessUnknown: '이용 시간 알 수 없음', route: '도보 경로 열기', changeWarning: '정보가 변경되었을 수 있습니다. 도착 시 이용 가능 여부를 확인하세요.', coverage: '지원 지역 및 출처' },
  pt: { emergency: 'EMERGÊNCIA', callFirst: 'Ligue primeiro para 119', cpr: 'Inicie a RCP. Peça a outra pessoa para buscar o AED.', call: 'LIGAR', findTitle: 'Mostre a direção do AED', useLocation: 'Usar minha localização', privacy: 'Nada é armazenado ou enviado', demo: 'Testar demonstração de Tóquio', locating: 'Localizando…', nearest: 'AED listado mais próximo', straightLine: 'linha reta', open24: 'Listado como 24 horas', accessUnknown: 'Acesso desconhecido', route: 'Abrir rota a pé', changeWarning: 'Os dados podem ter mudado — confirme o acesso ao chegar.', coverage: 'Cobertura e fontes' },
  es: { emergency: 'EMERGENCIA', callFirst: 'Llame primero al 119', cpr: 'Inicie la RCP. Pida a otra persona que busque el AED.', call: 'LLAMAR', findTitle: 'Indíqueme un AED', useLocation: 'Usar mi ubicación', privacy: 'No se guarda ni envía nada', demo: 'Probar demostración de Tokio', locating: 'Buscando su ubicación…', nearest: 'AED registrado más cercano', straightLine: 'línea recta', open24: 'Indicado como 24 horas', accessUnknown: 'Acceso desconocido', route: 'Abrir ruta a pie', changeWarning: 'Los datos pueden haber cambiado; confirme el acceso al llegar.', coverage: 'Cobertura y fuentes' },
  vi: { emergency: 'KHẨN CẤP', callFirst: 'Gọi 119 trước', cpr: 'Bắt đầu hồi sức tim phổi. Nhờ người khác đi lấy AED.', call: 'GỌI', findTitle: 'Chỉ hướng đến AED', useLocation: 'Dùng vị trí của tôi', privacy: 'Vị trí không được lưu hoặc gửi đi', demo: 'Thử bản demo trung tâm Tokyo', locating: 'Đang tìm vị trí…', nearest: 'AED gần nhất trong danh sách', straightLine: 'đường thẳng', accessUnknown: 'Chưa rõ thời gian tiếp cận', route: 'Mở tuyến đường đi bộ', coverage: 'Phạm vi và nguồn dữ liệu' },
  tl: { emergency: 'EMERHENSIYA', callFirst: 'Tumawag muna sa 119', cpr: 'Simulan ang CPR. Magpakuha ng AED sa ibang tao.', call: 'TAWAG', findTitle: 'Ituro ako sa AED', useLocation: 'Gamitin ang lokasyon ko', privacy: 'Hindi iniimbak o ipinapadala ang lokasyon', demo: 'Subukan ang demo sa Tokyo', locating: 'Hinahanap ang lokasyon…', nearest: 'Pinakamalapit na nakalistang AED', straightLine: 'tuwirang layo', accessUnknown: 'Hindi alam ang access', route: 'Buksan ang rutang lakaran', coverage: 'Saklaw at mga pinagmulan' },
  ne: { emergency: 'आपतकालीन', callFirst: 'पहिले 119 मा फोन गर्नुहोस्', cpr: 'CPR सुरु गर्नुहोस्। अर्को व्यक्तिलाई AED लिन पठाउनुहोस्।', call: 'फोन', findTitle: 'मलाई AED तर्फ देखाउनुहोस्', useLocation: 'मेरो स्थान प्रयोग गर्नुहोस्', privacy: 'स्थान सुरक्षित वा पठाइँदैन', demo: 'टोकियो डेमो चलाउनुहोस्', locating: 'स्थान पत्ता लगाउँदै…', nearest: 'सबैभन्दा नजिकको सूचीबद्ध AED', straightLine: 'सीधा दूरी', accessUnknown: 'पहुँच समय अज्ञात', route: 'हिँड्ने बाटो खोल्नुहोस्', coverage: 'कभरेज र स्रोतहरू' },
  id: { emergency: 'DARURAT', callFirst: 'Telepon 119 terlebih dahulu', cpr: 'Mulai CPR. Minta orang lain mengambil AED.', call: 'TELEPON', findTitle: 'Arahkan saya ke AED', useLocation: 'Gunakan lokasi saya', privacy: 'Lokasi tidak disimpan atau dikirim', demo: 'Coba demo pusat Tokyo', locating: 'Mencari lokasi…', nearest: 'AED terdaftar terdekat', straightLine: 'garis lurus', accessUnknown: 'Akses tidak diketahui', route: 'Buka rute jalan kaki', coverage: 'Cakupan dan sumber' },
  th: { emergency: 'ฉุกเฉิน', callFirst: 'โทร 119 ก่อน', cpr: 'เริ่มทำ CPR ให้ผู้อื่นไปนำ AED มา', call: 'โทร', findTitle: 'บอกทิศทางไปยัง AED', useLocation: 'ใช้ตำแหน่งของฉัน', privacy: 'ไม่บันทึกหรือส่งตำแหน่ง', demo: 'ทดลองตำแหน่งใจกลางโตเกียว', locating: 'กำลังค้นหาตำแหน่ง…', nearest: 'AED ที่อยู่ใกล้ที่สุดในรายการ', straightLine: 'ระยะทางเส้นตรง', accessUnknown: 'ไม่ทราบเวลาเข้าถึง', route: 'เปิดเส้นทางเดิน', coverage: 'พื้นที่ครอบคลุมและแหล่งข้อมูล' },
  hi: { emergency: 'आपातकाल', callFirst: 'पहले 119 पर कॉल करें', cpr: 'CPR शुरू करें। किसी दूसरे व्यक्ति को AED लाने भेजें।', call: 'कॉल', findTitle: 'मुझे AED की दिशा दिखाएँ', useLocation: 'मेरी जगह का उपयोग करें', privacy: 'जगह सहेजी या भेजी नहीं जाती', demo: 'मध्य टोक्यो डेमो आज़माएँ', locating: 'आपकी जगह खोजी जा रही है…', nearest: 'सबसे नज़दीकी सूचीबद्ध AED', straightLine: 'सीधी दूरी', accessUnknown: 'पहुँच का समय अज्ञात', route: 'पैदल मार्ग खोलें', coverage: 'कवरेज और स्रोत' },
  fr: { emergency: 'URGENCE', callFirst: 'Appelez d’abord le 119', cpr: 'Commencez la RCP. Demandez à une autre personne d’aller chercher le DAE.', call: 'APPELER', findTitle: 'Indiquez-moi un DAE', useLocation: 'Utiliser ma position', privacy: 'La position n’est ni stockée ni envoyée', demo: 'Essayer la démo du centre de Tokyo', locating: 'Localisation en cours…', nearest: 'DAE répertorié le plus proche', straightLine: 'à vol d’oiseau', accessUnknown: 'Accès inconnu', route: 'Ouvrir l’itinéraire à pied', coverage: 'Couverture et sources' },
  ru: { emergency: 'ЭКСТРЕННО', callFirst: 'Сначала позвоните 119', cpr: 'Начните СЛР. Попросите другого человека принести AED.', call: 'ЗВОНОК', findTitle: 'Покажите направление к AED', useLocation: 'Использовать моё местоположение', privacy: 'Местоположение не сохраняется и не отправляется', demo: 'Демо в центре Токио', locating: 'Определяем местоположение…', nearest: 'Ближайший AED из списка', straightLine: 'по прямой', accessUnknown: 'Доступ неизвестен', route: 'Открыть пеший маршрут', coverage: 'Охват и источники' },
};

export function messages(locale: Locale): Messages { return { ...en, ...(translations[locale] || {}) }; }

export function normalizeLocale(value?: string | null): Locale | null {
  if (!value) return null;
  const normalized = value.toLowerCase();
  if (normalized === 'zh-cn' || normalized === 'zh-sg' || normalized.startsWith('zh-hans')) return 'zh-Hans';
  if (normalized === 'zh-tw' || normalized === 'zh-hk' || normalized === 'zh-mo' || normalized.startsWith('zh-hant')) return 'zh-Hant';
  const exact = (Object.keys(localeNames) as Locale[]).find((locale) => locale.toLowerCase() === normalized);
  if (exact) return exact;
  const base = normalized.split('-')[0];
  return (Object.keys(localeNames) as Locale[]).find((locale) => locale === base) || null;
}
